if (NOT DEFINED CONFIG OR NOT DEFINED DST OR NOT DEFINED REDIST_DLLS)
    message(FATAL_ERROR "copy_msvc_redist.cmake requires -DCONFIG=<config>, -DDST=<dir>, and -DREDIST_DLLS=<dll-list>")
endif ()

foreach (_arg CONFIG DST REDIST_DLLS)
    if ("${${_arg}}" MATCHES "^\"(.*)\"$")
        set(${_arg} "${CMAKE_MATCH_1}")
    endif ()
endforeach ()

if (NOT REDIST_DLLS)
    message(STATUS "No MSVC redistributables were reported by InstallRequiredSystemLibraries.")
    return()
endif ()

set(_skip_reason "")
if (CONFIG STREQUAL "Debug")
    set(_skip_reason "Debug builds must not copy the non-debug MSVC redistributable DLLs")
endif ()

if (_skip_reason)
    message(STATUS "Skipping MSVC redistributable copy: ${_skip_reason}.")
    foreach (_dll IN LISTS REDIST_DLLS)
        get_filename_component(_name "${_dll}" NAME)
        set(_stale "${DST}/${_name}")
        if (EXISTS "${_stale}")
            message(STATUS "Removing stale MSVC redistributable from this output: ${_stale}")
            file(REMOVE "${_stale}")
        endif ()
    endforeach ()
    return()
endif ()

file(MAKE_DIRECTORY "${DST}")

foreach (_dll IN LISTS REDIST_DLLS)
    if (NOT EXISTS "${_dll}")
        message(FATAL_ERROR "MSVC redistributable listed by CMake does not exist: ${_dll}")
    endif ()

    message(STATUS "Copying MSVC redistributable: ${_dll} -> ${DST}")
    file(COPY "${_dll}" DESTINATION "${DST}")
endforeach ()
