if (COMMAND sdrpp_collect_required_dep_roots)
    return()
endif ()

function(_sdrpp_normalize_dep_list out_var raw_value)
    set(_list "${raw_value}")
    string(REPLACE "," ";" _list "${_list}")
    string(REGEX REPLACE "[ \t\r\n]+" ";" _list "${_list}")
    list(FILTER _list EXCLUDE REGEX "^$")
    list(REMOVE_DUPLICATES _list)
    set(${out_var} ${_list} PARENT_SCOPE)
endfunction()

function(sdrpp_collect_required_dep_roots out_var)
    set(_deps fftw3 libcurl volk zstd)

    if (OPT_BACKEND_GLFW)
        list(APPEND _deps glfw3)
    endif ()

    if (OPT_BUILD_AIRSPY_SOURCE)
        list(APPEND _deps libairspy)
    endif ()
    if (OPT_BUILD_AIRSPYHF_SOURCE)
        list(APPEND _deps libairspyhf)
    endif ()
    if (OPT_BUILD_AUDIO_SOURCE OR OPT_BUILD_AUDIO_SINK)
        list(APPEND _deps rtaudio)
    endif ()
    if (OPT_BUILD_BADGESDR_SOURCE)
        list(APPEND _deps libusb)
    endif ()
    if (OPT_BUILD_BLADERF_SOURCE)
        list(APPEND _deps libbladeRF)
    endif ()
    if (OPT_BUILD_DAB_DECODER OR OPT_BUILD_M17_DECODER)
        list(APPEND _deps codec2)
    endif ()
    if (OPT_BUILD_FOBOSSDR_SOURCE)
        list(APPEND _deps libfobos)
    endif ()
    if (OPT_BUILD_HACKRF_SOURCE)
        list(APPEND _deps libhackrf)
    endif ()
    if (OPT_BUILD_HYDRASDR_RFONE_SOURCE)
        list(APPEND _deps libhydrasdr)
    endif ()
    if (OPT_BUILD_LIMESDR_SOURCE)
        list(APPEND _deps LimeSuite)
    endif ()
    if (OPT_BUILD_NEW_PORTAUDIO_SINK OR OPT_BUILD_PORTAUDIO_SINK)
        list(APPEND _deps portaudio)
    endif ()
    if (OPT_BUILD_PERSEUS_SOURCE)
        list(APPEND _deps libperseus-sdr)
    endif ()
    if (OPT_BUILD_PLUTOSDR_SOURCE)
        list(APPEND _deps libiio libad9361)
    endif ()
    if (OPT_BUILD_RADIOSONDE_DECODER)
        list(APPEND _deps sondedump)
    endif ()
    if (OPT_BUILD_QMX_SOURCE AND ANDROID)
        list(APPEND _deps libusb)
    endif ()
    if (DEFINED OPT_BUILD_SDDC_SOURCE AND OPT_BUILD_SDDC_SOURCE)
        list(APPEND _deps libusb)
    endif ()
    if (OPT_BUILD_RFNM_SOURCE)
        list(APPEND _deps librfnm)
    endif ()
    if (OPT_BUILD_RTL_SDR_SOURCE)
        list(APPEND _deps librtlsdr)
    endif ()
    if (OPT_BUILD_SDRPLAY_SOURCE)
        list(APPEND _deps sdrplay)
    endif ()

    list(REMOVE_DUPLICATES _deps)
    set(${out_var} ${_deps} PARENT_SCOPE)
endfunction()